#Yes, stuff goes here
#Format: name = "url"
[github]
thatrnpr = {val = "https://github.com/thatrandomperson5", author = "thatrandomperson5"}
lolerz = {val = "https://github.com/l/o/l/e/r/z", author = "thatrandomperson5"}
