#Yes, stuff goes here
#Format: name = "url"
[github]
thatrnpr = {val = "https://github.com/thatrandomperson5", author = "thatrandomperson5"}
lol = {val = "https://github.com/l/o/l", author = "thatrandomperson5"}
