name: check_pull
on:
  pull_request:
    types:
      - opened
      - labeled
jobs:
  auto_label:
    runs-on: ubuntu-latest

    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"   
  verify:
    if: github.event.label.name == 'register'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install tomli
      - run: python actions/verify.py
      
