name: check_pull

on:
  pull_request_target:
   types: [opened, labeled]
jobs:
   verify:
       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v3
         - name: check_labels
           uses: jesusvasquez333/verify-pr-label-action@v1.4.0
           with:
             github-token: '${{ secrets.GITHUB_TOKEN }}'
             valid-labels: 'register'
             invalid-labels: 'bug, invalid'
             pull-request-number: '${{ github.event.pull_request.number }}'
