name: check_pull
on:
  pull_request:
    types:
      - opened
      - labeled
jobs:
  auto_label:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.transfer.outputs.labels }}
    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"   
    - id: transfer
      run: |
       echo "::set-output name=labels::$(gh api --jq '.labels.[].name' /repos/${GITHUB_REPOSITORY%/*}/${{ github.event.repository.name }}/pulls/${{ github.event.number }})\n"
      env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  verify:
    needs: auto_label
    if: needs.auto_label.outputs.labels == 'register'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install tomli
      - run: python actions/verify.py
        env:
            author: github.event.pull_request.user.login
          
  review_blame:
    if: github.event.label.name == 'register'
    needs: auto_label
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install GitPython
      - run: python actions/review_blame.py
