name: check_pull

on:
  pull_request:
   types: [opened, labeled]
jobs:
   verify:
       if: ${{ github.event.label.name == 'register' }}
       runs-on: ubuntu-latest
       
       steps:
       - uses: actions/checkout@v2
       - name: Run a one-line script
         run: echo Hello, world!
   stage2:
       runs-on: ubuntu-latest
       needs: verify
       steps:
       - uses: actions/checkout@v2
       - name: Run a one-line script
         run: echo Hello, world!       
       
        
       
